POST https://aifundryeastus5524573897.openai.azure.com/openai/responses
Content-Type: application/json
api-key: <API-KEY>

{
"model": "o3-mini"
 "prompt": [
  "tell me a joke about mango"
 ],
 "max_tokens": 32,
 "temperature": 1.0,
 "n": 1
}
